version: '3'

services:
  # Database container for dev
  database:
    image: mariadb:10.5.10
    env_file:
      - .env
    volumes:
      - database:/var/lib/mysql
    ports:
      # Expose port if you want to connect to database with a DB software like MySQL Workbench
      - "${MYSQL_PORT:-3307}:3306"
    restart: "no"

  # Database container for tests
  database_test:
    image: mariadb:10.5.10
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=api_recipes_book_test
      - MYSQL_USER=api_recipes_book_test
      - MYSQL_PASSWORD=api_recipes_book_test
    volumes:
      # Use tmpFS to increase database performance
      -   type: tmpfs
          target: /var/lib/mysql
    ports:
      # Expose port if you want to connect to databse with a DB software like MySQL Workbench
      - "${MYSQL_TEST_PORT:-3308}:3306"
    restart: "no"

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
